### ISSUE TITLE
Message property in factoryValidation should be overriden!

### ISSUE THREAD

**Issue by Robinhoodbharadwaj** [highercomve/valida-js#11]
Hi,
I was using your library and find it pretty good in writing my own validation engine, one suggestion of mine would be to override the message property in each of the default validation methods, if user has provided it's own message key, then i think it's better to provide that custom message rather than library's own. `message || message(...)` will do the trick.

Thanks

**Comment by highercomve** [comment]
Thanks, I could add those changes.

But I added a way to create personalized messages, but I think i didn't add that to the documentation.

Right now what you could do is

```
const rules = ValidaJs.rulesCreator(ValidaJs.validators, [
  {
    name: 'firstName',
    type: 'required',
    stateMap: 'firstName'
  },
  {
    name: 'email',
    type: 'required',
    stateMap: 'email',
    message: (value, errorType, key) => `${key} is invalid (${errorType}) because ${value} `
  },
  {
    name: 'email',
    type: 'isEmail',
    stateMap: 'email'
  },
  {
    name: 'email',
    type: 'minLength',
    stateMap: 'email',
    compareWith: 10
  }
])
```

the full message function structure is

```
 (value, errorType, key, compareWith) => ``
```
